"""empty message

Revision ID: 3e028e04752a
Revises: 4deee33799e7
Create Date: 2022-03-25 20:03:03.615494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e028e04752a'
down_revision = '4deee33799e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_projects', sa.Column('due', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_projects', 'due')
    # ### end Alembic commands ###
